### ISSUE TITLE
when entering world/joining on lan, it kicks player out on first try,only allows in after restart. every single time.

### ISSUE THREAD

**Issue by agr21** [ercanserteli/xercamods#30]
using 1.16.4, if i enter the world or join a friend, it kick me out/crashes the game on first try, have to restart it. every time. here is what i am getting as single player:
(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
java.lang.NullPointerException
	at net.minecraft.advancements.PlayerAdvancements.func_192743_a(PlayerAdvancements.java:332)
	at net.minecraft.advancements.PlayerAdvancements.func_192747_a(PlayerAdvancements.java:325)
	at net.minecraft.advancements.PlayerAdvancements.func_192744_b(PlayerAdvancements.java:226)
	at xerca.xercamod.common.EventHandler.onPlayerLoggedIn(EventHandler.java:114)
	at net.minecraftforge.eventbus.ASMEventHandler_394_EventHandler_onPlayerLoggedIn_PlayerLoggedInEvent.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
	at net.minecraftforge.fml.hooks.BasicEventHooks.firePlayerLoggedIn(BasicEventHooks.java:44)
	at net.minecraft.server.management.PlayerList.func_72355_a(PlayerList.java:231)
	at net.minecraft.network.login.ServerLoginNetHandler.func_147326_c(ServerLoginNetHandler.java:118)
	at net.minecraft.network.login.ServerLoginNetHandler.func_73660_a(ServerLoginNetHandler.java:65)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:222)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:134)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:864)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:786)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:118)
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:641)
	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:232)
	at java.lang.Thread.run(Unknown Source)

[14Feb2021 01:14:24.216] [Server thread/FATAL] [net.minecraftforge.common.ForgeMod/]: Preparing crash report with UUID 3c7b05f1-6352-4805-b0f5-a291e42ed761
[14Feb2021 01:14:24.216] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: Encountered an unexpected exception
net.minecraft.crash.ReportedException: Ticking memory connection
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:137) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:864) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:786) ~[?:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:118) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:641) ~[?:?]
	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:232) ~[?:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_261]
Caused by: java.lang.NullPointerException
	at net.minecraft.advancements.PlayerAdvancements.func_192743_a(PlayerAdvancements.java:332) ~[?:?]
	at net.minecraft.advancements.PlayerAdvancements.func_192747_a(PlayerAdvancements.java:325) ~[?:?]
	at net.minecraft.advancements.PlayerAdvancements.func_192744_b(PlayerAdvancements.java:226) ~[?:?]
	at xerca.xercamod.common.EventHandler.onPlayerLoggedIn(EventHandler.java:114) ~[xercamod:1.16.4-1.3]
	at net.minecraftforge.eventbus.ASMEventHandler_394_EventHandler_onPlayerLoggedIn_PlayerLoggedInEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.fml.hooks.BasicEventHooks.firePlayerLoggedIn(BasicEventHooks.java:44) ~[forge:?]
	at net.minecraft.server.management.PlayerList.func_72355_a(PlayerList.java:231) ~[?:?]
	at net.minecraft.network.login.ServerLoginNetHandler.func_147326_c(ServerLoginNetHandler.java:118) ~[?:?]
	at net.minecraft.network.login.ServerLoginNetHandler.func_73660_a(ServerLoginNetHandler.java:65) ~[?:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:222) ~[?:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:134) ~[?:?]

at at joining(from host's log):
(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
java.lang.NullPointerException
	at net.minecraft.advancements.PlayerAdvancements.func_192743_a(PlayerAdvancements.java:332)
	at net.minecraft.advancements.PlayerAdvancements.func_192747_a(PlayerAdvancements.java:325)
	at net.minecraft.advancements.PlayerAdvancements.func_192744_b(PlayerAdvancements.java:226)
	at xerca.xercamod.common.EventHandler.onPlayerLoggedIn(EventHandler.java:114)
	at net.minecraftforge.eventbus.ASMEventHandler_655_EventHandler_onPlayerLoggedIn_PlayerLoggedInEvent.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
	at net.minecraftforge.fml.hooks.BasicEventHooks.firePlayerLoggedIn(BasicEventHooks.java:44)
	at net.minecraft.server.management.PlayerList.func_72355_a(PlayerList.java:231)
	at net.minecraft.network.login.ServerLoginNetHandler.func_147326_c(ServerLoginNetHandler.java:118)
	at net.minecraft.network.login.ServerLoginNetHandler.func_73660_a(ServerLoginNetHandler.java:65)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:222)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:134)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:864)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:786)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:118)
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:641)
	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:232)
	at java.lang.Thread.run(Unknown Source)

[14Feb2021 01:19:44.504] [Server thread/WARN] [net.minecraft.network.NetworkSystem/]: Failed to handle packet for /192.168.1.20:61360
java.lang.NullPointerException: null
	at net.minecraft.advancements.PlayerAdvancements.func_192743_a(PlayerAdvancements.java:332) ~[?:?]
	at net.minecraft.advancements.PlayerAdvancements.func_192747_a(PlayerAdvancements.java:325) ~[?:?]
	at net.minecraft.advancements.PlayerAdvancements.func_192744_b(PlayerAdvancements.java:226) ~[?:?]
	at xerca.xercamod.common.EventHandler.onPlayerLoggedIn(EventHandler.java:114) ~[xercamod:1.16.4-1.3]
	at net.minecraftforge.eventbus.ASMEventHandler_655_EventHandler_onPlayerLoggedIn_PlayerLoggedInEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.fml.hooks.BasicEventHooks.firePlayerLoggedIn(BasicEventHooks.java:44) ~[forge:?]
	at net.minecraft.server.management.PlayerList.func_72355_a(PlayerList.java:231) ~[?:?]
	at net.minecraft.network.login.ServerLoginNetHandler.func_147326_c(ServerLoginNetHandler.java:118) ~[?:?]
	at net.minecraft.network.login.ServerLoginNetHandler.func_73660_a(ServerLoginNetHandler.java:65) ~[?:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:222) ~[?:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:134) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:864) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:786) ~[?:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:118) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:641) ~[?:?]
	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:232) ~[?:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_261]

**Comment by DamienBrittan** [comment]
have the same f*ing issue :c really love this mod but i spend 3 days trying to figure out what the hell is wrong with my minecraft modpack . only thing is that i play 1.16.5 and singleplayer . Stuck everytime at loading my world for no reason at all

**Comment by ercanserteli** [comment]
This should be hopefully fixed in the new version. Let me know if you still experience this after updating.
 711d70a1

**Comment by agr21** [comment]
works just fine now, thanks!
