### ISSUE TITLE
[Joy of Painting] Mod Loading Crash

### ISSUE THREAD

**Issue by scribe-of-days** [ercanserteli/xercamods#51]
Hey Xerca,

I'm getting the following crash log when I try to load the game with your mod as part of a custom modpack I'm developing. Could you help me figure out what's going on here? Would really love to include it if at all possible!

---- Minecraft Crash Report ----

// Shall we play a game?

Time: 1/30/22, 10:24 PM

Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed

at net.minecraftforge.logging.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:69) ~[forge-1.18.1-39.0.64-universal.jar%2389!/:?] {re:classloading}

at net.minecraftforge.client.loading.ClientModLoader.completeModLoading(ClientModLoader.java:183) ~[forge-1.18.1-39.0.64-universal.jar%2389!/:?] {re:classloading,pl:runtimedistcleaner:A}

at net.minecraft.client.Minecraft.lambda$new$1(Minecraft.java:553) ~[client-1.18.1-20211210.034407-srg.jar%2385!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:terrablender_forge.mixins.json:client.MixinMinecraft,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}

at net.minecraft.Util.m_137521_(Util.java:409) ~[client-1.18.1-20211210.034407-srg.jar%2385!/:?] {re:classloading}

at net.minecraft.client.Minecraft.lambda$new$2(Minecraft.java:547) ~[client-1.18.1-20211210.034407-srg.jar%2385!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:terrablender_forge.mixins.json:client.MixinMinecraft,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}

at net.minecraft.client.gui.screens.LoadingOverlay.m_6305_(LoadingOverlay.java:135) ~[client-1.18.1-20211210.034407-srg.jar%2385!/:?] {re:classloading,pl:runtimedistcleaner:A}

at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:875) ~[client-1.18.1-20211210.034407-srg.jar%2385!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}

at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1040) ~[client-1.18.1-20211210.034407-srg.jar%2385!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:terrablender_forge.mixins.json:client.MixinMinecraft,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}

at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:660) ~[client-1.18.1-20211210.034407-srg.jar%2385!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:terrablender_forge.mixins.json:client.MixinMinecraft,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}

at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.1-20211210.034407-srg.jar%2385!/:?] {re:classloading,pl:runtimedistcleaner:A}

at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}

at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}

at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}

at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}

at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:45) ~[fmlloader-1.18.1-39.0.64.jar%2323!/:?] {}

at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.0.jar%235!/:?] {}

at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.0.jar%235!/:?] {}

at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.0.jar%235!/:?] {}

at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.0.jar%235!/:?] {}

at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.0.jar%235!/:?] {}

at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.0.jar%235!/:?] {}

at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.0.jar%235!/:?] {}

at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:

---------------------------------------------------------------------------------------

-- Head --

Thread: Render thread

Stacktrace:

at java.util.HashMap.computeIfAbsent(HashMap.java:1221) ~[?:?] {re:mixin}

-- MOD xercapaint --

Details:

Mod File: xercapaint-1.18.1-0.7.0 (1).jar

Failure message: Joy of Painting (xercapaint) encountered an error during the sided_setup event phase

java.util.ConcurrentModificationException: null

Mod Version: 1.18.1-0.7.0

Mod Issue URL: NOT PROVIDED

Exception message: java.util.ConcurrentModificationException

Stacktrace:

at java.util.HashMap.computeIfAbsent(HashMap.java:1221) ~[?:?] {re:mixin}

at net.minecraft.client.renderer.item.ItemProperties.register(ItemProperties.java:60) ~[client-1.18.1-20211210.034407-srg.jar%2385!/:?] {re:classloading,pl:runtimedistcleaner:A}

at xerca.xercapaint.client.ClientStuff$ModBusSubscriber.clientSetupHandler(ClientStuff.java:94) ~[xercapaint-1.18.1-0.7.0%20(1).jar%2384!/:1.18.1-0.7.0] {re:classloading}

at net.minecraftforge.eventbus.ASMEventHandler_25_ModBusSubscriber_clientSetupHandler_FMLClientSetupEvent.invoke(.dynamic) ~[?:?] {}

at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%232!/:?] {}

at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?] {}

at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?] {}

at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:120) ~[javafmllanguage-1.18.1-39.0.64.jar%2387!/:?] {}

at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:121) ~[fmlcore-1.18.1-39.0.64.jar%2386!/:?] {}

at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}

at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}

at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}

at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}

at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {}

at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {}

at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

-- System Details --

Details:

Minecraft Version: 1.18.1

Minecraft Version ID: 1.18.1

Operating System: Windows 10 (amd64) version 10.0

Java Version: 17.0.1, Microsoft

Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft

Memory: 1842301952 bytes (1756 MiB) / 5364514816 bytes (5116 MiB) up to 7784628224 bytes (7424 MiB)

CPUs: 12

Processor Vendor: GenuineIntel

Processor Name: Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz

Identifier: Intel64 Family 6 Model 158 Stepping 10

Microarchitecture: Coffee Lake

Frequency (GHz): 2.21

Number of physical packages: 1

Number of physical CPUs: 6

Number of logical CPUs: 12

Graphics card #0 name: Intel(R) UHD Graphics 630

Graphics card #0 vendor: Intel Corporation (0x8086)

Graphics card #0 VRAM (MB): 1024.00

Graphics card #0 deviceId: 0x3e9b

Graphics card #0 versionInfo: DriverVersion=27.20.100.8681

Graphics card #1 name: NVIDIA GeForce GTX 1060

Graphics card #1 vendor: NVIDIA (0x10de)

Graphics card #1 VRAM (MB): 4095.00

Graphics card #1 deviceId: 0x1c20

Graphics card #1 versionInfo: DriverVersion=27.21.14.6230

Memory slot #0 capacity (MB): 16384.00

Memory slot #0 clockSpeed (GHz): 2.67

Memory slot #0 type: DDR4

Virtual memory max (MB): 46957.95

Virtual memory used (MB): 25358.63

Swap memory total (MB): 30720.00

Swap memory used (MB): 1567.70

JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx7424m -Xms256m

ModLauncher: 9.1.0+9.1.0+main.6690ee51

ModLauncher launch target: forgeclient

ModLauncher naming: srg

ModLauncher services:

mixin PLUGINSERVICE

eventbus PLUGINSERVICE

object_holder_definalize PLUGINSERVICE

runtime_enum_extender PLUGINSERVICE

capability_token_subclass PLUGINSERVICE

accesstransformer PLUGINSERVICE

runtimedistcleaner PLUGINSERVICE

mixin TRANSFORMATIONSERVICE

fml TRANSFORMATIONSERVICE

FML Language Providers:

minecraft@1.0

kotlinforforge@3.1.0

javafml@null

Mod List:

client-1.18.1-20211210.034407-srg.jar |Minecraft |minecraft |1.18.1 |ENQUEUE_IM|Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f

QuarkOddities-1.18.jar |Quark Oddities |quarkoddities |1.18 |ENQUEUE_IM|Manifest: NOSIGNATURE

TerraBlender-forge-1.18.1-1.1.0.73.jar |TerraBlender |terrablender |1.18.1-1.1.0.73 |ENQUEUE_IM|Manifest: NOSIGNATURE

supermartijn642configlib-1.0.9-mc1.18.jar |SuperMartijn642's Config Lib |supermartijn642configlib |1.0.9 |ENQUEUE_IM|Manifest: NOSIGNATURE

ImmersiveEngineering-1.18.1-7.1.0-145.jar |Immersive Engineering |immersiveengineering |1.18.1-7.1.0-145 |ENQUEUE_IM|Manifest: 44:39:94:cf:1d:8c:be:3c:7f:a9:ee:f4:1e:63:a5:ac:61:f9:c2:87:d5:5b:d9:d6:8c:b5:3e:96:5d:8e:3f:b7

rechiseled-1.0.8-mc1.18.jar |rechiseled |rechiseled |1.0.8 |ENQUEUE_IM|Manifest: NOSIGNATURE

supermartijn642corelib-1.0.16a-mc1.18.jar |SuperMartijn642's Core Lib |supermartijn642corelib |1.0.16a |ENQUEUE_IM|Manifest: NOSIGNATURE

Architects-Palette-1.18.1-1.0.0.jar |Architect's Palette |architects_palette |1.1.2 |ENQUEUE_IM|Manifest: NOSIGNATURE

flywheel-forge-1.18-0.6.0.jar |Flywheel |flywheel |1.18-0.6.0 |ENQUEUE_IM|Manifest: NOSIGNATURE

curios-forge-1.18.1-5.0.6.0.jar |Curios API |curios |1.18.1-5.0.6.0 |ENQUEUE_IM|Manifest: NOSIGNATURE

CuriosQuarkOBP-1.18.1-1.1.0.jar |Curios Quark Oddities Backpack|curiosquarkobp |1.1.0 |ENQUEUE_IM|Manifest: NOSIGNATURE

create-mc1.18.1_v0.4d.jar |Create |create |0.4d |ENQUEUE_IM|Manifest: NOSIGNATURE

waystones-forge-1.18.1-9.0.3.jar |Waystones |waystones |9.0.3 |ENQUEUE_IM|Manifest: NOSIGNATURE

cookingforblockheads-forge-1.18.1-11.1.0.jar |CookingForBlockheads |cookingforblockheads |11.1.0 |ENQUEUE_IM|Manifest: NOSIGNATURE

citadel-1.10.8-1.18.jar |Citadel |citadel |1.10.8 |ENQUEUE_IM|Manifest: NOSIGNATURE

alexsmobs-1.16.0.jar |Alex's Mobs |alexsmobs |1.16.0 |ENQUEUE_IM|Manifest: NOSIGNATURE

AutoRegLib-1.7-52.jar |AutoRegLib |autoreglib |1.7-52 |ENQUEUE_IM|Manifest: NOSIGNATURE

xercapaint-1.18.1-0.7.0 (1).jar |Joy of Painting |xercapaint |1.18.1-0.7.0 |ERROR |Manifest: NOSIGNATURE

mightyarchitect-mc1.18.1_v0.6.jar |The Mighty Architect |mightyarchitect |0.6 |ENQUEUE_IM|Manifest: NOSIGNATURE

architectury-3.5.12.jar |Architectury |architectury |3.5.12 |ENQUEUE_IM|Manifest: NOSIGNATURE

stonecutter_recipe_tags-2.0.1.jar |Stonecutter Recipe Tags |stonecutter_recipe_tags |2.0.1 |ENQUEUE_IM|Manifest: NOSIGNATURE

balm-2.4.2+0.jar |Balm |balm |2.4.2+0 |ENQUEUE_IM|Manifest: NOSIGNATURE

Adorn-3.2.0+1.18.1-forge.jar |Adorn |adorn |3.2.0+1.18.1 |ENQUEUE_IM|Manifest: NOSIGNATURE

Oh The Biomes You'll Go-forge-1.18.1-1.3.5.8.jar |Oh The Biomes You'll Go |byg |1.3.5.8 |ENQUEUE_IM|Manifest: NOSIGNATURE

forge-1.18.1-39.0.64-universal.jar |Forge |forge |39.0.64 |ENQUEUE_IM|Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90

Quark-3.0-334.jar |Quark |quark |3.0-334 |ENQUEUE_IM|Manifest: NOSIGNATURE

supplementaries-1.18.1-1.1.11.jar |Supplementaries |supplementaries |1.1.11 |ENQUEUE_IM|Manifest: NOSIGNATURE

ChiselsBits-forge-1.18.1-1.2.77-universal.jar |Chisels & bits |chiselsandbits |1.2.77 |ENQUEUE_IM|Manifest: NOSIGNATURE

xercamusic-1.18.1-0.9.0.jar |Xerca's Music Maker Mod |xercamusic |1.18.1-0.9.0 |ENQUEUE_IM|Manifest: NOSIGNATURE

Terralith_v2.0.12_Fabric+Forge.jar |Seed Fix + Terralith |seedfix_forge |0.0NONE |ENQUEUE_IM|Manifest: NOSIGNATURE

refinedstorage-1.10.0.jar |Refined Storage |refinedstorage |1.10.0 |ENQUEUE_IM|Manifest: NOSIGNATURE

refinedstorageaddons-0.8.1.jar |Refined Storage Addons |refinedstorageaddons |0.8.1 |ENQUEUE_IM|Manifest: NOSIGNATURE

selene-1.18-1.12.0.jar |Selene |selene |1.18-1.12.0 |ENQUEUE_IM|Manifest: NOSIGNATURE

chipped-1.18.1-1.2.1-forge.jar |Chipped |chipped |1.18.1-1.2.1-forge |ENQUEUE_IM|Manifest: NOSIGNATURE

Flywheel Backend: GL33 Instanced Arrays

Crash Report UUID: 9b2f01a6-f20e-4d72-8e4c-8014310b0e87

FML: 39.0

Forge: net.minecraftforge:39.0.64

**Comment by scribe-of-days** [comment]
Just wanted to add, reverting to the previous version works and doesn't result in a crash, so it's just this most recent version that's having an issue.

**Comment by ercanserteli** [comment]
Thanks for posting this issue. It should be fixed now with 678fe52. I just published the new version as 1.18.1 - 0.7.1.
