### ISSUE TITLE
Crashing when trying to paint. (v1.0.0) (mc v1.20.1)

### ISSUE THREAD

**Issue by Haano137** [ercanserteli/xercamods#96]
```
---- Minecraft Crash Report ----
// Why did you do that?

Time: 2023-08-05 16:10:37
Description: Rendering entity in world

java.lang.NullPointerException: Cannot invoke "xerca.xercapaint.client.RenderEntityCanvas.getCanvasRendererInstance(net.minecraft.class_2487, int, int)" because "xerca.xercapaint.client.RenderEntityCanvas.theInstance" is null
	at xerca.xercapaint.client.CanvasItemRenderer.method_3166(CanvasItemRenderer.java:41)
	at xerca.xercapaint.client.EaselCanvasLayer.render(EaselCanvasLayer.java:58)
	at xerca.xercapaint.client.EaselCanvasLayer.method_4199(EaselCanvasLayer.java:14)
	at xerca.xercapaint.client.RenderEntityEasel.lambda$render$0(RenderEntityEasel.java:69)
	at java.base/java.util.ArrayList.forEach(Unknown Source)
	at xerca.xercapaint.client.RenderEntityEasel.render(RenderEntityEasel.java:69)
	at xerca.xercapaint.client.RenderEntityEasel.method_3936(RenderEntityEasel.java:28)
	at net.minecraft.class_898.method_3954(class_898.java:145)
	at net.minecraft.class_761.method_22977(class_761.java:1574)
	at net.minecraft.class_761.method_22710(class_761.java:1324)
	at net.minecraft.class_757.method_3188(class_757.java:1110)
	at net.minecraft.class_757.method_3192(class_757.java:880)
	at net.minecraft.class_310.method_1523(class_310.java:1219)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at xerca.xercapaint.client.CanvasItemRenderer.method_3166(CanvasItemRenderer.java:41)
	at xerca.xercapaint.client.EaselCanvasLayer.render(EaselCanvasLayer.java:58)
	at xerca.xercapaint.client.EaselCanvasLayer.method_4199(EaselCanvasLayer.java:14)
	at xerca.xercapaint.client.RenderEntityEasel.lambda$render$0(RenderEntityEasel.java:69)
	at java.base/java.util.ArrayList.forEach(Unknown Source)
	at xerca.xercapaint.client.RenderEntityEasel.render(RenderEntityEasel.java:69)
	at xerca.xercapaint.client.RenderEntityEasel.method_3936(RenderEntityEasel.java:28)
	at net.minecraft.class_898.method_3954(class_898.java:145)
	at net.minecraft.class_761.method_22977(class_761.java:1574)
	at net.minecraft.class_761.method_22710(class_761.java:1324)
	at net.minecraft.class_757.method_3188(class_757.java:1110)

-- Entity being rendered --
Details:
	Entity Type: xercapaint:easel (xerca.xercapaint.entity.EntityEasel)
	Entity ID: 1809
	Entity Name: entity.xercapaint.easel
	Entity's Exact location: 25.50, 84.00, 16.50
	Entity's Block location: World: (25,84,16), Section: (at 9,4,0 in 1,5,1; chunk contains blocks 16,-64,16 to 31,319,31), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at net.minecraft.class_898.method_3954(class_898.java:145)
	at net.minecraft.class_761.method_22977(class_761.java:1574)
	at net.minecraft.class_761.method_22710(class_761.java:1324)
	at net.minecraft.class_757.method_3188(class_757.java:1110)
	at net.minecraft.class_757.method_3192(class_757.java:880)
	at net.minecraft.class_310.method_1523(class_310.java:1219)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)

-- Renderer details --
Details:
	Assigned renderer: xerca.xercapaint.client.RenderEntityEasel@82fa3c0
	Location: 2.05,-1.62,-0.13 - World: (2,-2,-1), Section: (at 2,14,15 in 0,-1,-1; chunk contains blocks 0,-64,-16 to 15,319,-1), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,-64,-512 to 511,319,-1)
	Rotation: 90.0
	Delta: 0.32008755
Stacktrace:
	at net.minecraft.class_898.method_3954(class_898.java:145)
	at net.minecraft.class_761.method_22977(class_761.java:1574)
	at net.minecraft.class_761.method_22710(class_761.java:1324)
	at net.minecraft.class_757.method_3188(class_757.java:1110)
	at net.minecraft.class_757.method_3192(class_757.java:880)
	at net.minecraft.class_310.method_1523(class_310.java:1219)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)

-- Affected level --
Details:
	All players: 1 total; [class_746['Haano'/408, l='ClientLevel', x=23.45, y=84.00, z=16.63]]
	Chunk stats: 1024, 625
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,86,0), Section: (at 0,6,0 in 0,5,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 2053 game time, 2053 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:458)
	at net.minecraft.class_310.method_1587(class_310.java:2406)
	at net.minecraft.class_310.method_1514(class_310.java:821)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, fabric, file/Chat Reporting Helper.zip, file/Fast Better Grass.zip, continuity:default, continuity:glass_pane_culling_fix, file/xbr-all-the-fish-dry-edition.zip, file/§dNya§fPack.zip, file/UniqueDark_1.20.1.zip, file/SimpleHotbar.zip, file/FreshAnimations_v1.8.1.zip, file/Foliage+ Tweaks V1.0.1.zip, file/Foliage+ V1.5.9.3.zip, elytratrims:default

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.6, Azul Systems, Inc.
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Azul Systems, Inc.
	Memory: 354860216 bytes (338 MiB) / 2067791872 bytes (1972 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 16
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 7 5800H with Radeon Graphics         
	Identifier: AuthenticAMD Family 25 Model 80 Stepping 0
	Microarchitecture: Zen 3
	Frequency (GHz): 3.19
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: AMD Radeon(TM) Graphics
	Graphics card #0 vendor: Advanced Micro Devices, Inc. (0x1002)
	Graphics card #0 VRAM (MB): 512.00
	Graphics card #0 deviceId: 0x1638
	Graphics card #0 versionInfo: DriverVersion=27.20.14032.15001
	Graphics card #1 name: NVIDIA GeForce RTX 3060 Laptop GPU
	Graphics card #1 vendor: NVIDIA (0x10de)
	Graphics card #1 VRAM (MB): 4095.00
	Graphics card #1 deviceId: 0x2520
	Graphics card #1 versionInfo: DriverVersion=31.0.15.3667
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Virtual memory max (MB): 29036.07
	Virtual memory used (MB): 21798.77
	Swap memory total (MB): 13312.00
	Swap memory used (MB): 187.89
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx4096m
	Fabric Mods: 
		accurateblockplacement: Accurate Block Placement 1.0.17
		animatica: Animatica 0.6+1.20
		appleskin: AppleSkin 2.5.0+mc1.20
		architectury: Architectury 9.1.12
		autocomplete: AutoComplete 1.1
		autoreconnect: AutoReconnect 2.2.1
		balm-fabric: Balm 7.0.7
		bettercommandblockui: BetterCommandBlockUI 0.4.2
		borderlessmining: Borderless Mining 1.1.8+1.20.1
		cameraoverhaul: Camera Overhaul 1.4.0-fabric-universal
		capes: Capes 1.5.2+1.20
		chat_heads: Chat Heads 0.10.19
		chatpatches: Chat Patches 201.5.3
		chesttracker: Chest Tracker 1.1.22
			libgui: LibGui 8.0.0+1.20
				jankson: Jankson 5.0.1+j1.2.2
				libninepatch: LibNinePatch 1.2.0
			whereisit: Where Is It 1.14.17
		citresewn: CIT Resewn 1.1.3+1.20
			citresewn-defaults: CIT Resewn: Defaults 1.1.3+1.20
		clean_tooltips: Clean Tooltips 1.0
		cloth-config: Cloth Config v11 11.1.106
			cloth-basic-math: cloth-basic-math 0.6.1
		completionistsindex: Completionist's Index 8.0.0
		continuity: Continuity 3.0.0-beta.3+1.20.1
		craterlib: CraterLib 1.0.2
		customskinloader: CustomSkinLoader 14.17
		draggable_lists: Draggable Lists 1.0.0
		dynamicfps: Dynamic FPS 2.4.0
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
		ears: Ears 1.4.6
		elytraslot: Elytra Slot 6.3.0+1.20.1
		elytratrims: Elytra Trims 1.1.10-beta.4
			com_github_llamalad7_mixinextras: MixinExtras 0.2.0-beta.9
			conditional-mixin: conditional mixin 0.3.2
		emi: EMI 1.0.17+1.20.1+fabric
		emi_loot: EMI Loot 0.6.5+1.20.1
		emuno: EmuNO 1.1.0
		enhancedblockentities: Enhanced Block Entities 0.9+1.20
			advanced_runtime_resource_pack: Runtime Resource Pack 0.6.7
			spruceui: SpruceUI 5.0.0+1.20
		entity_model_features: Entity Model Features 0.2.13
		entity_texture_features: Entity Texture Features 4.4.4
			org_apache_httpcomponents_httpmime: httpmime 4.5.10
		entityculling: EntityCulling-Fabric 1.6.2-mc1.20
		equipmentcompare: Equipment Compare 1.3.7
			cardinal-components-base: Cardinal Components API (base) 5.2.0
			cardinal-components-entity: Cardinal Components API (entities) 5.2.0
		fabric-api: Fabric API 0.86.1+1.20.1
			fabric-api-base: Fabric API Base 0.4.30+7abfd51577
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.35+4d8536c977
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.10+b3afc78b77
			fabric-block-api-v1: Fabric Block API (v1) 1.0.9+e022e5d177
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.40+b3afc78b77
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.1+97bb207577
			fabric-command-api-v1: Fabric Command API (v1) 1.2.33+f71b366f77
			fabric-command-api-v2: Fabric Command API (v2) 2.2.12+b3afc78b77
			fabric-commands-v0: Fabric Commands (v0) 0.2.50+df3654b377
			fabric-containers-v0: Fabric Containers (v0) 0.1.62+df3654b377
			fabric-content-registries-v0: Fabric Content Registries (v0) 4.0.9+b3afc78b77
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.4+a1a980da77
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.18+aeb40ebe77
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 12.2.1+1e61dba177
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.52+b3afc78b77
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.22+b3afc78b77
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.1+e91849a877
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.62+df3654b377
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.38+b04edc7a77
			fabric-item-api-v1: Fabric Item API (v1) 2.1.27+b3afc78b77
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.10+23d9108177
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.36+fb8d95da77
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.34+df3654b377
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.21+b3afc78b77
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.39+b3afc78b77
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.43+9e7660c677
			fabric-message-api-v1: Fabric Message API (v1) 5.1.7+3265161977
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.49+b3afc78b77
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.2+709a987177
			fabric-models-v0: Fabric Models (v0) 0.4.1+9386d8a777
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.9+b3afc78b77
			fabric-networking-v0: Fabric Networking (v0) 0.3.49+df3654b377
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 11.1.1+6beca84877
			fabric-particles-v1: Fabric Particles (v1) 1.1.1+201a23a077
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.19+b3afc78b77
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.3.1+4df89eb277
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.1.1+9386d8a777
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.4.1+9172968c77
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.45+df3654b377
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.34+b3afc78b77
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.27+b3afc78b77
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.48+df3654b377
			fabric-rendering-v1: Fabric Rendering (v1) 3.0.7+b3afc78b77
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.5+ea08f9d877
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.9+132c48c177
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.7+b3afc78b77
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.28+b3afc78b77
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.12+b3afc78b77
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.3.0+cdf060b277
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 4.3.0+6c31357e77
		fabric-language-kotlin: Fabric Language Kotlin 1.10.8+kotlin.1.9.0
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.9.0
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.9.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.9.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.9.0
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.21.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.7.2
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.7.2
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.5.1
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.5.1
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.5.1
		fabricloader: Fabric Loader 0.14.21
		fabricskyboxes: FabricSkyBoxes 0.7.2+mc1.20.1
		farmersdelight: Farmer's Delight 1.20.1-1.4.1
		fastquit: FastQuit 3.0.0-beta.2+1.20+
		ferritecore: FerriteCore 6.0.0
		fix-keyboard-on-linux: Fix Keyboard on Linux 1.0.0
		forgeconfigapiport: Forge Config API Port 8.0.0
		fsb-interop: FabricSkyBoxes Interop 1.3.3+mc1.20-build.46
		handcrafted: Handcrafted 2.3.2
		horsestatsvanilla: Horse Stats Vanilla 4.3.0
		iceberg: Iceberg 1.1.13
		immediatelyfast: ImmediatelyFast 1.1.20+1.20.1
			net_lenni0451_reflect: Reflect 1.2.1
		incendium: Incendium 5.3.1
		indium: Indium 1.0.21+mc1.20.1
		inventoryprofilesnext: Inventory Profiles Next 1.10.6
		invmove: InvMove 0.8.4
		iris: Iris 1.6.4
			io_github_douira_glsl-transformer: glsl-transformer 2.0.0-pre13
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.11.1
		isxander-main-menu-credits: Main Menu Credits 1.1.2
		java: OpenJDK 64-Bit Server VM 17
		journeymap: Journeymap 5.9.12
			journeymap-api-fabric: JourneyMap API 1.20-1.9-fabric-SNAPSHOT
		kaffees_dual_ride: Kaffee's Dual Ride 1.1.0
		lambdynlights: LambDynamicLights 2.3.1+1.20.1
			pride: Pride Lib 1.2.0+1.19.4
		libipn: libIPN 3.0.2
		libjf: LibJF 3.10.2
			libjf-base: LibJF Base 3.10.2
			libjf-config-commands-v1: LibJF Config Commands 3.10.2
			libjf-config-core-v1: LibJF Config 3.10.2
			libjf-config-reflect-v1: LibJF Config Reflect 3.10.2
			libjf-config-ui-tiny-v1: LibJF Config UI: Tiny 3.10.2
			libjf-data-manipulation-v0: LibJF Data Manipulation 3.10.2
			libjf-data-v0: LibJF Data 3.10.2
			libjf-translate-v1: LibJF Translate 3.10.2
			libjf-unsafe-v0: LibJF Unsafe 3.10.2
			libjf-web-v0: LibJF Web 3.10.2
		lithium: Lithium 0.11.2
		mca: Minecraft Comes Alive 7.5.5+1.20.1
		minecraft: Minecraft 1.20.1
		modernfix: ModernFix 5.4.2+mc1.20.1
		modmenu: Mod Menu 7.2.1
		moreculling: More Culling 1.20-0.18.1
		nbt_ac: NBT Autocomplete 1.1.2
		no-resource-pack-warnings: No Resource Pack Warnings 1.3.0
		nullscape: Nullscape 1.2.2
		nyfsspiders: Nyf's Spiders 2.1.0
		optigui: OptiGUI 2.1.5
			optiglue: OptiGlue 2.1.5-mc.1.19.3
			org_apache_commons_commons-text: commons-text 1.10.0
			org_ini4j_ini4j: ini4j 0.5.4
		pack_it_up: Pack It Up! 0.3.1+1.20.1
		pickupnotifier: Pick Up Notifier 8.0.0
		presencefootsteps: Presence Footsteps 1.9.0
			kirin: Kirin UI 1.15.0
		puzzle: Puzzle 1.5.2+1.20
			midnightlib: MidnightLib 1.4.1
			puzzle-base: Puzzle Base 1.5.2+1.20
			puzzle-gui: Puzzle GUI 1.5.2+1.20
			puzzle-models: Puzzle Models 1.5.2+1.20
			puzzle-splashscreen: Puzzle Splash Screen 1.5.2+1.20
		puzzleslib: Puzzles Lib 8.0.15
		reeses-sodium-options: Reese's Sodium Options 1.6.3+mc1.20.1-build.92
		replanter-plus: Replanter Plus 1.0
		resourcefullib: Resourceful Lib 2.1.8
			com_teamresourceful_bytecodecs: bytecodecs 1.0.1
			com_teamresourceful_yabn: yabn 1.0.3
		resourcepackchecker: Server Resource Pack Checker 1.20.1-1.0.2
		resourcify: Resourcify 1.1.0
			elementa: Elementa 590+markdown
			universalcraft: UniversalCraft 269
		respackopts: Resource Pack Options 4.3.1
			io_gitlab_jfronny_muscript: muscript 1.3-SNAPSHOT
		rprenames: RP Renames 0.6.0
		simple-rpc: Simple RPC 3.2.2
			me_hypherionmc_simplerpc_simple-rpc-common: simple-rpc-common 5.0.0
		skinlayers: 3d Skin Layers 1.5.4-mc1.20.1
		slotswap: Slot Swap 1.1.0+mc1.20.1
		sodium: Sodium 0.4.10+build.27
		sodium-extra: Sodium Extra 0.4.23+mc1.20.1-build.106
			caffeineconfig: CaffeineConfig 1.3.0+1.17
			crowdin-translate: CrowdinTranslate 1.4+1.19.3
		sound_physics_remastered: Sound Physics Remastered 1.20.1-1.1.1
		spu: Server Pack Unlocker 1.6
		starlight: Starlight 1.1.2+fabric.dbc156f
		stendhal: Stendhal 1.3.9-1.20
		talkbubbles: Talk Bubbles 1.0.7
		terralith: Terralith 2.4.3
		threadtweak: ThreadTweak 1.20.1-0.1.0
		tooltipfix: ToolTip Fix 1.1.1-1.20
		transmog: Transmog 1.2.3+1.20
		trinkets: Trinkets 3.7.1
		vectorientation: Vectorientation 1.0.1a
		vmp: Very Many Players 0.2.0+beta.7.100
		wakes: Wakes 0.2.0
			blue_endless_jankson: jankson 1.2.2
		waystones: Waystones 14.0.1
		world-host: World Host 0.4.3
			org_quiltmc_qup_json: json 0.2.0
		xercamusic: Music Maker Mod fabric-1.20.1-1.0.0
		xercapaint: Joy of Painting fabric-1.20.1-1.0.0
		yet_another_config_lib_v3: YetAnotherConfigLib 3.1.0+1.20
			com_twelvemonkeys_common_common-image: common-image 3.10.0-SNAPSHOT
			com_twelvemonkeys_common_common-io: common-io 3.10.0-SNAPSHOT
			com_twelvemonkeys_common_common-lang: common-lang 3.10.0-SNAPSHOT
			com_twelvemonkeys_imageio_imageio-core: imageio-core 3.10.0-SNAPSHOT
			com_twelvemonkeys_imageio_imageio-metadata: imageio-metadata 3.10.0-SNAPSHOT
			com_twelvemonkeys_imageio_imageio-webp: imageio-webp 3.10.0-SNAPSHOT
		yosbr: YOSBR 0.1.2
		zoomify: Zoomify 2.10.0
			com_akuleshov7_ktoml-core-jvm: ktoml-core-jvm 0.4.1
			dev_isxander_settxi_settxi-core: settxi-core 2.10.6
			dev_isxander_settxi_settxi-kotlinx-serialization: settxi-kotlinx-serialization 2.10.6
	Loaded Shaderpack: (off)
	NEC status: No NEC detected
	Launched Version: 1.20.1
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: NVIDIA GeForce RTX 3060 Laptop GPU/PCIe/SSE2 GL version 3.2.0 NVIDIA 536.67, NVIDIA Corporation
	Window size: 1920x1001
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, fabric, file/Chat Reporting Helper.zip, file/Fast Better Grass.zip, continuity:default, continuity:glass_pane_culling_fix, file/xbr-all-the-fish-dry-edition.zip, file/§dNya§fPack.zip, file/UniqueDark_1.20.1.zip, file/SimpleHotbar.zip, file/FreshAnimations_v1.8.1.zip, file/Foliage+ Tweaks V1.0.1.zip, file/Foliage+ V1.5.9.3.zip, elytratrims:default
	Current Language: en_us
	CPU: 16x AMD Ryzen 7 5800H with Radeon Graphics 
	Server Running: true
	Player Count: 1 / 8; [class_3222['Haano'/408, l='ServerLevel[New World]', x=23.45, y=84.00, z=16.63]]
	Data Packs: vanilla, fabric
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Experimental
```

**Comment by Snowy893** [comment]
I'm getting the same bug! While I wasn't using the exact same mods it's the same

"Description: Rendering entity in world

java.lang.NullPointerException: Cannot invoke "xerca.xercapaint.client.RenderEntityCanvas.getCanvasRendererInstance(net.minecraft.class_2487, int, int)" because "xerca.xercapaint.client.RenderEntityCanvas.theInstance" is null"
[crash-2024-03-06_03.07.28-client.txt](https://github.com/ercanserteli/xercamods/files/14506828/crash-2024-03-06_03.07.28-client.txt)

**Comment by Snowy893** [comment]
I have no idea if this will fix it for you, but I noticed you also had modernfix in your mods list. There's this one setting in the modernfix config called "mixin.perf.dynamic_entity_renderers", which I had on (it's off by default). Turning it off fixed the issue!

If it doesn't fix it, maybe test removing puzzleslib? If I remember correctly I think it does change stuff with rendering that may also break Joy of Painting

**Comment by ercanserteli** [comment]
The crash should be fixed in the new version
